[package]
name = "Test"
version = "0.1.0"
authors = ["ultilect <lesin.bogdan1234@gmail.com>"]
edition = "2018"
default-run= "main"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
